### ISSUE TITLE
spec for website min replica

### ISSUE THREAD

**Issue by danielebriggi** [analitico/analitico#180]
Add to the yaml (same level of the second spec):
```
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        # autoscaling.knative.dev/maxScale: "10"
     spec:
      .....
```
